### ISSUE TITLE
EPD vs. Material

### ISSUE THREAD

**Issue by fe-ac** [jbf1212/ec3-python-wrapper#1]
Hi Jared - big fan of your work here.

This is not directly related to this repo but I was wondering if you could help me understand the difference between EPDs and Materials in EC3. Why is it necessary to have two separate API endpoints providing basically the same information? Sorry, I understand you did not create this structure, but I wasn't sure who else to turn to.

Thanks,
Arthur

**Comment by jbf1212** [comment]
Hi Arthur - thanks for the kind words. The EPD vs Materials endpoints in the API is definitely confusing. I don't have a great answer since I can't say I fully understand the exact delineation myself. Though conceptually one can imagine why they may be different - _EPDs_ refer to a document whereas _materials_ refer to a physical thing - there seems to be a  lot of overlap in the properties they carry. 

Here are my best guesses as to why they are different endpoints, but somebody from BuildingTransparency would really need to confirm this:

- There are a few different types of EPDs in the EC3 database: "Product EPDs", "Industry EPDs", "Generic Estimates". Whereas a "material" (if I understand correctly) only refers to specific products. Therefore conceptually, EPDs are a little broader.
- One can only create/upload an EPD in EC3. There is no functionality on the site or via the API to create a Material. Therefore, we can assume that for a material to exist, it must belong to an EPD.
- While I think there is currently a 1-to-1 mapping of materials to EPDs, one can imagine that you could potentially have a single material that points to multiple EPDs over time. For example, if the plant where a product is manufactured suddenly switched to a cleaner energy grid, the material itself didn't change, but the EPD would need to change. I definitely can't say whether or not this is actually the thinking here, but I can imagine that as a potential reason to delineate between EPD and material.

It looks like BT recently deprecated the way they previously queried materials and replaced it with a new [MaterialFilter](https://buildingtransparency.org/ec3/manage-apps/api-doc/guide#/03_Material_Filter/01_Material_Filter.md) approach. I haven't looked into this much yet, but it looks like I may need to go back and update how some of the functionality wrapping the materials queries is working in the wrapper. Maybe this update is an indication that they are trying to move away from the concept of materials as their own endpoint in order to address some of the confusion.
